---
- name: Running opencontrail init contrail for heat engine
  vars:
    heat_engine_svc: "{{ heat_services['heat-engine'] }}"
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    detach: False
    image: "{{ heat_opencontrail_init_image_full }}"
    labels:
      BOOTSTRAP:
    environment:
      OPENSTACK_VERSION: "{{ openstack_release }}"
    name: "bootstrap_heat_opencontrail_plugin"
    restart_policy: no
    volumes: "{{ heat_engine_svc.volumes|reject('equalto', '')|list }}"
  when:
    - neutron_plugin_agent == 'opencontrail'
    - heat_engine_svc.enabled | bool
